spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(UECTFwtwVbMluXKRlLfvzN5GB/UdVEfU/m/XD6ZzkTP4zTz3in0DOf6zEjA0Kbtb8lGQK3vKw2edCGwbXe9k//gfo0KbgIK2baTppeWTnNAC6Wv4s12ibgxBar9aNvWBj4PkZIFJ+fTyQU0xaoR8CA==)
            client-secret: ENC(gGsHRVHYjjKHYWxn8fXa51IiLEJG+XxsjWldE/H1VaaqXbARcbDxgFEBr0YZpW1iD80NIZBdRxLtOvwQe5MwD2QZtZlCg/S6pq6sOQZ+aEw=)
            scope:
              - email
              - profile
          facebook:
            client-id: ENC(hqdAIqis4LGjGG7TaezgdQpOvBuv3CWgb53J03pxaBli0pgZvuOgOnyxjzHSjb8H)
            client-secret: ENC(YKxCyF04l+T51RW4CmuePOD8YPwBYofX9Vf2J0xgGJxnRaIQBeMEeXC7zMhVQRAI+RX7bZYJnziPeUiG9gOE1l0+yqiMQW1+INhg0y0eroE=)
            scope:
              - email
              - public_profile
          github:
            client-id: ENC(e1RdT7YfP49iAcNywiOjLJc7tCf8RLONxGrWDAQuuwrduSIHOeX4/97pLDBpo+NFvUlSkKCaEEecpHg/qa/ZJQ==)
            client-secret: ENC(xOHfshXhDHs062AXFC4ZzI4wR3cZIh+FzfkGjkVhfetRcVev04TIensXbKnomxdbNTUb3r8IV5llRfpBLwzFehlL+F9XPiFwtMCNY6oWpZs=)
            scope:
              - user:email
              - read:user
  mail:
    host: smtp.gmail.com
    username: cabin.escape.room.web.app@gmail.com
    password: ENC(0ogSdWEtMpHaugOJXX2UiKbE0bMiQOpjy1TsOIC9PjXWcZ4hIg1Lm1vROHEYT/P7BmfIp85PacP3MDOftYT1Ig==)
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true