spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(ZXftkJehcx98+TOWPKUotdh7iTO4rIKH34JYy97pjA5Q1V7jXxmJ3LBhxYErLQtpYDo8MnmC6At3Yl7G8HEfI6lXLc+w6IMje2D/kDzcMOU0UP8PZvr23lHG4CidgR/eWiwNXeP4bmw2zTO02bhVjg==)
            client-secret: ENC(IikNE3tS6/kEMZtWxfnKP0XDD62T54yg2Z6qJxjYqwa1R6kqCGPs35aq7LvdDmRUBg6iXWjjvf/TMdRQcW4wbvC03gia4YBD01KqzPOkE4w=)
            scope:
              - email
              - profile
          facebook:
            client-id: ENC(JzpmizaXdw5gI9o6mjK0eLYyOOxtDSK7R819QUUZ4EnbqpPePFmkhadDtxUpHm6j)
            client-secret: ENC(cVDiohHhoIChMeusvbwHjRFDUDHHdGYQfSrNAGKu1qn+LOW9IDwHhUtmWpXxPeQUhKGYnYfO0pgo+GLtlIi4B1Fon+lLHb24kH0c4O384ME=)
            scope:
              - email
              - public_profile
          github:
            client-id: ENC(fqZQSd56zUp0kWMoOmPR8HqXPc5Msbij18GXxV2yK521ovLbjwbtmBQ1oDZCImIEjSBBEYrM4o52BEV0n3kwwg==)
            client-secret: ENC(3sPJcfOni59PP0dbqBEFdcDW8yMB2DDYLH8tkbErMnuBZ3fUhObMyWwOrm8pG6mF6Crsm71M58nZYSP7M3DVYpj1JxTOILbX9sKObQM/xFQ=)
            scope:
              - user:email
              - read:user
  mail:
    host: smtp.gmail.com
    username: cabin.escape.room.web.app@gmail.com
    password: ENC(0ogSdWEtMpHaugOJXX2UiKbE0bMiQOpjy1TsOIC9PjXWcZ4hIg1Lm1vROHEYT/P7BmfIp85PacP3MDOftYT1Ig==)
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true